const config = {
    PORT: 3000,
    DISCORD_TOKEN: "TU_DISCORD_TOKEN",
    DISCORD_CHANNEL_ID: "1498678945812447389",
    GEMINI_API: "TU_GEMINI_API_KEY",
    SUPABASE_URL: "TU_SUPABASE_URL",
    SUPABASE_ANON_KEY: "TU_SUPABASE_ANON_KEY",
};

module.exports = config;
