const config = {
    PORT: 3000,
    DISCORD_TOKEN: "TU_DISCORD_TOKEN",
    DISCORD_CHANNEL_ID: "1498678945812447389",
    GEMINI_API: "TU_GEMINI_API_KEY",
    SUPABASE_URL: "TU_SUPABASE_URL",
    SUPABASE_ANON_KEY: "TU_SUPABASE_ANON_KEY",
    TWITTER_API_KEY: "TU_TWITTER_API_KEY",
    TWITTER_API_SECRET: "TU_TWITTER_API_SECRET",
    TWITTER_ACCESS_TOKEN: "TU_TWITTER_ACCESS_TOKEN",
    TWITTER_ACCESS_SECRET: "TU_TWITTER_ACCESS_SECRET",
    REDDIT_CLIENT_ID: "TU_REDDIT_CLIENT_ID",
    REDDIT_CLIENT_SECRET: "TU_REDDIT_CLIENT_SECRET",
    REDDIT_USERNAME: "TU_REDDIT_USERNAME",
    REDDIT_PASSWORD: "TU_REDDIT_PASSWORD",
    REDDIT_USER_AGENT: "TalentCircle/1.0",
};

module.exports = config;
